apiVersion: apps/v1
kind: Deployment
metadata:
  name: downwork
spec: 
  replicas: 2
  selector:
    matchLabels:
      app: downwork
  template:
    metadata:
      labels:
        app: downwork
    spec:
      containers:
      - name: downwork
        image: shan117/downwork:latest
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: downwork-config
        ports:
        - containerPort: 3000
